### ISSUE TITLE
Hide internal identifier from user

### ISSUE THREAD

**Issue by zhan1182** [zhan1182/JP_Morgan_Chase_Team_2#3]
Hide the order identifier from the frontend. Users don't care about the identifier. As long as they can execute many different orders, we are good.

**Comment by zhan1182** [comment]
Issue from demo

**Comment by mw10104587** [comment]
Auto generates id by checking how many orders we currently have. 
E.G. if we have 2 ongoing orders and 1 finished order, the next id will be 3. (Starting from 0)
8e5c3e295f277cda913ff687ab762d60d7a6c020

**Comment by mw10104587** [comment]
Auto generates id by checking how many orders we currently have. 
E.G. if we have 2 ongoing orders and 1 finished order, the next id will be 3. (Starting from 0)
8e5c3e295f277cda913ff687ab762d60d7a6c020
